name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-latest, macos-13, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: linux install stuff
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libudev-dev libv4l-dev
    - name: Set environment variables
      run: |
        echo "OS=`echo ${RUNNER_OS} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_ENV
        echo "ARCH=`echo ${RUNNER_ARCH} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_ENV
        echo "AARCH=`echo ${RUNNER_ARCH} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_ENV
        if [[ ${{ runner.os }} == "macOS" ]]
        then
          if [[ ${{ runner.arch }} != "X64" ]]
          then
            echo "AARCH=aarch64" >> $GITHUB_ENV
          fi
        fi
      shell: bash
    - name: Setup Java and Apache Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'
        server-id: gluon-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
    - name: Download and extract JEXTRACT (default)
      if: runner.os != 'Windows'
      run: |
        download_url="https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_${{ env.OS }}-${{ env.AARCH }}_bin.tar.gz"
        wget -q --show-progress -O $RUNNER_TEMP/jextract.tar.gz $download_url
        tar -xvzf $RUNNER_TEMP/jextract.tar.gz -C $GITHUB_WORKSPACE
        echo "JEXTRACT=${GITHUB_WORKSPACE}/jextract-22" >> $GITHUB_ENV
    - name: Download and extract JEXTRACT (Windows)
      if: runner.os == 'Windows'
      run: |
        $ProgressPreference = "SilentlyContinue"
        Invoke-WebRequest https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_${{ env.OS }}-${{ env.ARCH }}_bin.tar.gz -OutFile jextract.tar.gz
        tar -xvzf jextract.tar.gz -C $env:GITHUB_WORKSPACE
        echo "JEXTRACT=$env:GITHUB_WORKSPACE\jextract-22" >> $env:GITHUB_ENV
        del jextract.tar.gz
      shell: powershell
    - name: Make Project
      run: |
        make java
      shell: bash
    - name: Publish Snapshots
      if: github.ref == 'refs/heads/main'
      run: |
        # Find version
        ver=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        if [[ $ver == *"SNAPSHOT"* ]]
        then
            make deploy
        fi
      shell: bash
      env:
        MAVEN_USERNAME: ${{ secrets.GLUON_NEXUS_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.GLUON_NEXUS_PASSWORD }}
