name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-latest, macos-13, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: linux install stuff
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libudev-dev libv4l-dev
    - name: Set environment variables
      run: |
        echo "OS_LOWER=`echo ${RUNNER_OS} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_ENV
        echo "ARCH=`echo ${RUNNER_ARCH} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_ENV
        echo "AARCH=`echo ${RUNNER_ARCH} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_ENV
        if [[ ${{ runner.os }} == "macOS" ]]
        then
          if [[ ${{ runner.arch }} != "X64" ]]
          then
            echo "AARCH=aarch64" >> $GITHUB_ENV
          fi
        fi
      shell: bash
    - name: Setup Java and Apache Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23.0.2'
        server-id: gluon-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
    - name: Download and extract JEXTRACT (default)
      if: runner.os != 'Windows'
      run: |
        download_url="https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_${{ env.OS_LOWER }}-${{ env.AARCH }}_bin.tar.gz"
        wget -q --show-progress -O $RUNNER_TEMP/jextract.tar.gz $download_url
        tar -xvzf $RUNNER_TEMP/jextract.tar.gz -C $GITHUB_WORKSPACE
        echo "JEXTRACT=${GITHUB_WORKSPACE}/jextract-22" >> $GITHUB_ENV
    - name: Download and extract JEXTRACT (Windows)
      if: runner.os == 'Windows'
      run: |
        $ProgressPreference = "SilentlyContinue"
        Invoke-WebRequest https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_${{ env.OS_LOWER }}-${{ env.ARCH }}_bin.tar.gz -OutFile jextract.tar.gz
        tar -xvzf jextract.tar.gz -C $env:GITHUB_WORKSPACE
        echo "JEXTRACT=$env:GITHUB_WORKSPACE\jextract-22" >> $env:GITHUB_ENV
        del jextract.tar.gz
      shell: powershell
    - name: Publish Release
      run: make deploy
      env:
        MAVEN_USERNAME: ${{ secrets.GLUON_NEXUS_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.GLUON_NEXUS_PASSWORD }}

  update-version:
    runs-on: ubuntu-24.04
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Commit next development version
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          NEW_PROJECT_VERSION=${TAG%.*}.$((${TAG##*.} + 1))
          echo "Update development version to $NEW_PROJECT_VERSION"
          mvn -ntp versions:set -DnewVersion=$NEW_PROJECT_VERSION-SNAPSHOT -DgenerateBackupPoms=false
          git config --global user.name 'Gluon Bot'
          git config --global user.email 'gluon-bot@users.noreply.github.com'
          git commit pom.xml -m "Prepare development of $NEW_PROJECT_VERSION"
          git push https://gluon-bot:$PAT@github.com/$GITHUB_REPOSITORY HEAD:main
        shell: bash
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
